### PR TITLE
CCD-4097: Auto-suppress CVEs - Node JS apps

### PR DESCRIPTION
**Pull request by JamesCollettCGI**
### JIRA link ###
https://tools.hmcts.net/jira/browse/CCD-4097

### Change description ###
Initial version of GitHub Workflow to auto-suppress CVEs for Node JS project.
Essentially it does the following :-
1. Backup previous yarn-audit-known-issues
2. Run yarn audit
3. Append new suppressions to yarn-audit-new-issues report

**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by JamesCollettCGI** [comment]
**PIPELINE:** https://build.platform.hmcts.net/job/HMCTS_a_to_c/job/ccd-admin-web/view/change-requests/job/PR-537/

**Review by rajaram-nagarajan — CHANGES_REQUESTED** [review]
we should have only one suppression file. The same can be done for all other nodejs app as well

**Review by rajaram-nagarajan — APPROVED** [review]
LGTM

**Review by rajaram-nagarajan — APPROVED** [review]
LGTM

**Pull request merged**
